.TH "SVCTL" 1 "Apr 2020" "Cem Keylan" "General Commands Manual"
.SH NAME
\fBsvctl\fR - sysmgr service controller
.SH SYNOPSIS
svctl \fI<command>\fR \fI[serv] [serv] [serv]\fR
.SH "COMMANDS"
.nf
start/stop/restart   Starts/stops/restarts a service
kill                 Sends a SIGKILL to the service
once                 Starts a service and does not restart it if it goes down.
status               Check if the service is running or not.
up/down              Same as start/stop
.fi
.SH "AUTHOR"
Cem Keylan
